name: Deploy to EC2 (Public Repo)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navegamos a la carpeta del proyecto
            cd /home/ec2-user/veterinaria
            
            # --- COMANDOS CORREGIDOS ---
            # Reemplazamos 'git pull' con un reseteo forzado.
            # Esto elimina cualquier cambio local en el servidor y lo deja idéntico al repo.
            # Es la forma correcta de hacerlo en un despliegue automático.
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            echo "✅ Repositorio reseteado a la última versión de main."
            
            # Instalamos dependencias
            npm install
            echo "✅ Dependencias instaladas."
            
            # Arreglamos el permiso de ejecución de Vite por si acaso
            chmod +x ./node_modules/.bin/vite
            echo "✅ Permisos de Vite corregidos."
            
            # Re-construimos el proyecto con los nuevos cambios
            npm run build
            echo "✅ Proyecto compilado."
            
            # Reiniciamos la aplicación con PM2
            pm2 restart veterinaria-app
            echo "🚀 Despliegue completado."