- name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navega a la carpeta del proyecto
            cd ${{ secrets.PROJECT_PATH }}
            echo "✅ Navegué a $(pwd)"

            # Descarga los últimos cambios
            git pull origin main
            echo "✅ Código actualizado desde GitHub."

            # Instala/actualiza las dependencias
            npm install
            echo "✅ Dependencias instaladas."

            # Compila la aplicación para producción
            npm run build
            echo "✅ Proyecto compilado con 'npm run build'."

            # 'restart' es robusto: si la app está corriendo, la recarga;
            # si se detuvo o dio error, la inicia de nuevo con el comando original.
            pm2 restart veterinaria-app
            echo "✅ Aplicación reiniciada con PM2."
            
            echo "🚀 Despliegue completado."
          EOF