name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: 'just-a-placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navega a la carpeta del proyecto
            cd ${{ secrets.PROJECT_PATH }}
            
            # Descarga los últimos cambios desde la rama main
            git pull origin main
            echo "✅ Código actualizado desde GitHub."
            
            # --- Comandos adicionales si los necesitas (ej. npm install) ---
            
            echo "🚀 Despliegue completado."
          EOF