name: Deploy to EC2 (Public Repo)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navegamos a la carpeta del proyecto
            cd /home/ec2-user/veterinaria
            
            # Traemos los últimos cambios
            git pull origin main
            echo "✅ Código actualizado."
            
            # Instalamos dependencias
            npm install
            echo "✅ Dependencias instaladas."
            
            # --- COMANDO CLAVE AÑADIDO ---
            # Arreglamos el permiso de ejecución de Vite por si acaso
            chmod +x ./node_modules/.bin/vite
            echo "✅ Permisos de Vite corregidos."
            
            # Re-construimos el proyecto con los nuevos cambios
            npm run build
            echo "✅ Proyecto compilado."
            
            # Reiniciamos la aplicación con PM2
            pm2 restart veterinaria-app
            echo "🚀 Despliegue completado."